### ISSUE TITLE
[frontend] impossible to update Service List provider

### ISSUE THREAD

**Issue by hacklsn** [DVBProject/DVB-I-Reference-CSR#12]
I have a couple of service lists entered already into my test CSR. For some I forgot to set the corect provider. 
When first creating a SL entry, there is multiple choice available for the provider field.
However, when chosing to edit the SL Offering, there is no multiple choice in the provider field. 
Entering the correct one manually and clicking "update" has no effect on the the wrong entry.
Leaving the field empty and clicking "update" has no effect either.

**Comment by juhajoki** [comment]
I believe this is a feature for now, but should be improved for sure.

**Comment by sofia-tsa** [comment]
Fixed in 0.16 release
