### ISSUE TITLE
Service List Genre should be selected from defined values

### ISSUE THREAD

**Issue by paulhiggs** [DVBProject/DVB-I-Reference-CSR#2]
The Genre (or Genres) for a Service List should be taken from any of the following classification schemes (branch and leaf elements are allowed)

- TV-Anytime [ContentCS](https://github.com/paulhiggs/dvb-i-tools/raw/main/tva/ContentCS.xml)
- TV-Anytime [FormatCS](https://raw.githubusercontent.com/paulhiggs/dvb-i-tools/main/tva/FormatCS.xml)
- DVB-I [ContentSubjectCS](https://github.com/paulhiggs/dvb-i-tools/raw/main/dvbi/DVBContentSubjectCS-2019.xml)

**Comment by juhajoki** [comment]
Paul, this should be done in tag 0.17
