### ISSUE TITLE
Creating default admin user

### ISSUE THREAD

**Issue by peterl1000** [DVBProject/DVB-I-Reference-CSR#3]
The default admin user is not created when installing and running the CSR for the first time.

Adding the line:
`INSERT INTO User(Name,Hash,Role,Organizations) VALUES("admin","$2a$08$7OhNJDnNMT46QIIK1dsEVeKmzf0hs4U0jvu3V4reNCdUt8Mj/RX4i","admin","0");
`
to the end of the db.sql file fixed the login issue for me, creating user "admin" with password "admin".

**Comment by juhajoki** [comment]
fixed in latest version, tagged 0.7
