### ISSUE TITLE
Editing Service List sometimes causes it to disappear

### ISSUE THREAD

**Issue by peterl1000** [DVBProject/DVB-I-Reference-CSR#5]
Editing a Service List entry sometimes causes it to disappear from the list of Service List in the front end.

Steps to recreate:

- Click "Add Service List"
- Enter Name and URI. Use defaults for other items
- Click "Add List"
- Click on the new list
- Change the name, or add a country (or maybe other things too)
- Click "Update"
- List is no longer shown in the list of Service Lists.

**Comment by peterl1000** [comment]
When I click "update", the backend shows the following debug output and the list is then not shown in the list of Service Lists.

```
update ServiceList {
  Name: 'peter2',
  lang: [],
  URI: 'peter1.com',
  Provider: 'Servicelist provider',
  regulatorList: 1,
  Delivery: [ 'DASHDelivery' ],
  Countries: [],
  Genres: []
} 14
removeAllListEntries 14 ServiceListName
removeAllListEntries 14 ServiceListURI
removeAllListEntries 14 Genre
removeAllListEntries 14 TargetCountry
removeAllListEntries 14 Language
updated List:  { id: '14' }
getAll: 66.082ms
```

**Comment by juhajoki** [comment]
thanks. 
Looks like if any of the optional fields is empty, and the service list is then updated, the list disappears from the service list list. That is how this is consistently reproducible.

**Comment by peterl1000** [comment]
I see the same - if I fill in more fields, the list does not disappear on update.

**Comment by ama-sfd** [comment]
I think I've found the root cause. Creating a new PR from the dev-branch.
