### ISSUE TITLE
Cannot add servicelist

### ISSUE THREAD

**Issue by removogel** [DVBProject/DVB-I-Reference-CSR#6]
After click "Add Service List" the page is empty. There seems to be a JS error.  
Chrome Version 96.0.4664.110  & Firefox 95 @ Ubuntu 21.10

![image](https://user-images.githubusercontent.com/8896037/146244726-2c92ed3b-6edf-4214-83a2-eb72846ca75f.png)

**Comment by juhajoki** [comment]
this was due to an empty provider name in the provider list. name has been added. a check for empty string needs to be added.

**Comment by ama-sfd** [comment]
This fix should be in the next release.
