### ISSUE TITLE
Cant' delete provider

### ISSUE THREAD

**Issue by removogel** [DVBProject/DVB-I-Reference-CSR#7]
After bulk adding of
Test provider 7
Test provider 8
I select them, switch to edit mode. Pressing "Delete" button has no effect.

**Comment by juhajoki** [comment]
this is due to cascade delete not implemented yet. it is only possible to delete providers which do not have service lists.

**Comment by ama-sfd** [comment]
This should now be fixed in my latest update, lists are now manually deleted and logged, before the provider is deleted.
